### PR TITLE
ADD ARRAY ELEMENTS

### PR DESCRIPTION
**Pull request by Yashika25**
Description to problem is added.

### CODE REVIEW

**Comment by Yashika25** [comment]
Description added.

**Review by Kvaibhav01 — CHANGES_REQUESTED** [review]
Again, check for space in between the hash (#) and the next letter. Like: # ARRAY SUM OF SIZE N.

Nicely explained!

**Comment by Yashika25** [comment]
Changes have been made. Please check.

**Review by Kvaibhav01 — APPROVED** [review]
Awesome work!

**Pull request merged**
